name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Create Credential File
        run: printf "%s" "${{ secrets.CLASPRC_JSON }}" | base64 --decode > ~/.clasprc.json

      - name: Validate Apps Script Files
        run: |
          test -f .clasp.json
          test -f appsscript.json
          test -f code.gs

      - name: Push Code
        run: clasp push -f

      - name: Deploy & Versioning
        run: |
          # Getting the current time in IST (India Standard Time)
          TIMESTAMP=$(TZ='Asia/Kolkata' date +'%Y-%m-%d %I:%M %p')
          clasp deploy -i AKfycbx8uNCOMiRgnYNaUSHGUJkUA3mZODDEh_MM7sW-dy33QGjsdCIQg7hLlEnvWbGPxnj9 -d "GitHub Auto-Deploy: $TIMESTAMP"
